# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20170418_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AbilityRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('primary', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClassFeature',
            fields=[
                ('feature_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('ancestors', models.ManyToManyField(blank=True, related_name='_feat_ancestors_+', to='player.Feat')),
                ('children', models.ManyToManyField(blank=True, related_name='_feat_children_+', to='player.Feat')),
                ('class_features', models.ManyToManyField(to='player.ClassFeature')),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='level',
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='features',
            field=models.ManyToManyField(to='player.ClassFeature'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Character'),
        ),
        migrations.AddField(
            model_name='characterability',
            name='character_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Character'),
        ),
        migrations.AddField(
            model_name='characterability',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Ability'),
        ),
        migrations.AddField(
            model_name='abilityrequirement',
            name='feat_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feat_id', to='player.Feat'),
        ),
        migrations.AddField(
            model_name='abilityrequirement',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Ability'),
        ),
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.ManyToManyField(to='player.Feat'),
        ),
    ]
